#!/usr/bin/env python3
""" takes abbreviation and expansion to add to espanso yml """
import os
import sys
import subprocess

yml = "/Users/pg/.config/espanso/user/phil.yml"
new = ''
exists = False
print(len(sys.argv))

if len(sys.argv) <= 2:
    # output all
    done = True
    trigger = False
    replaceStr = ''
else:
    done   = False
    replaceStr = ' '.join(sys.argv[2:])
    trigger = (f'  - trigger: "{sys.argv[1]}"\n')
replace = (f'    replace: "{replaceStr}"\n')

with open(yml,"r") as f:
    lines = f.readlines()
print("     phil.yml  ")
print(" trigger  replace")
print(" ________________")
for l in lines:
    if l.startswith("#"):
        print(l.split("#")[1].split("\n")[0])
    if exists:
        l = replace
        done = True
        print("Updated:")
    if l.startswith("  - trigger:"):
        trig = l.split('"')[1]
    if l.startswith("    replace:"):
        repl = l.split('"')[1]
        print(f"  {trig:<8}{repl}")
    exists = l == trigger
    new += l

if not done:
    new += (f"{trigger}{replace}")
    print("Added")
    print(f"  {sys.argv[1]:<8}{replaceStr}")

with open(yml,"w") as f:
    f.write(new)
print("")
subprocess.call('espanso restart', shell=True)
