#!/usr/bin/env python3
""" takes a list of files and moves them into folder named after the first file """
import os
from os import path
import sys
import shutil

# files arive as space separated list
files = sys.argv[1:][0].split(' ')
# first file without extension is new folder
folder = files[0].split('.')[0]
os.mkdir(folder)
# all files get moved to folder
for f in files:
    shutil.move(f,folder+'/'+f)
    thumb = (f'.{f}')
    if path.isfile(thumb):
        shutil.move(thumb,folder+'/'+thumb)

