#!/usr/bin/env python3
""" take speed (km/h) return pace min:sec (1:38.3) """

import sys
try:
    v = float(sys.argv[1])
    print(f'{1800/v//60:.0f}:{1800/v%60:04.1f}')
except:
    m,s = sys.argv[1].split(':')
    s = float(s) + 60 * int(m)
    print(f'{1800/s:.1f} km/h')
