#!/usr/bin/env python3
import sys
from renew import db
if __name__ == "__main__":
    try:
        db.getDF(sys.argv[1]).to_csv("sql.tab", index=False, sep="\t")
    except:
        with open("sql.tab",'w') as f:
            f.write(f'SQL error in: {sys.argv[1]}')
    print("result written to sql.tab")
